"""Se agregan campos a tabla de sismos

Revision ID: 031a77815691
Revises: 6f64bb3b4405
Create Date: 2022-10-26 13:29:25.180422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031a77815691'
down_revision = '6f64bb3b4405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sismo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profundidad', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hora', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sismo', schema=None) as batch_op:
        batch_op.drop_column('hora')
        batch_op.drop_column('profundidad')

    # ### end Alembic commands ###
