"""User model

Revision ID: 07d3a89cde53
Revises: 031a77815691
Create Date: 2022-10-28 16:17:34.489920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d3a89cde53'
down_revision = '031a77815691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('sismo', schema=None) as batch_op:
        batch_op.drop_column('hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sismo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.DATETIME(), nullable=True))

    op.drop_table('user')
    # ### end Alembic commands ###
