"""Se agrega id de los archivos en registro

Revision ID: 5cc269740fab
Revises: 53ee9f3b028a
Create Date: 2022-10-25 18:24:44.356768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc269740fab'
down_revision = '53ee9f3b028a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estacion', ['clave'])
    op.create_unique_constraint(None, 'instituto', ['clave'])
    op.add_column('registro', sa.Column('id_archivo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registro', 'id_archivo')
    op.drop_constraint(None, 'instituto', type_='unique')
    op.drop_constraint(None, 'estacion', type_='unique')
    # ### end Alembic commands ###
