"""Se agrega id de los archivos en registro

Revision ID: 6f64bb3b4405
Revises: 78a4aa692fd8
Create Date: 2022-10-25 18:31:58.576022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f64bb3b4405'
down_revision = '78a4aa692fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_archivo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('id_archivo')

    # ### end Alembic commands ###
